### ISSUE TITLE
Recording & Streaming is not working with latest version of jibri

### ISSUE THREAD

**Issue by adarshsingh6162** [kpeiruza/jitsi-images#1]
Thank you very much for this customization. I was using jibri image from this repo in k8 with auto-scaling enabled from last four months and it was working like a charm.
Now in latest version of jibri, it supports live streaming on any RTMP server. I replaced jibri.jar with new build but it stopped working after that. Will you please have a look and update this repo with latest build.
Thanks in advance.

**Comment by congthang1** [comment]
did you try latest image: kpeiruza/jibri:20210112

**Comment by kpeiruza** [comment]
Me/we did it :-)

El dj., 14 de gen. 2021, 17:21, Cong Thang <notifications@github.com> va
escriure:

**Comment by adarshsingh6162** [comment]
Yes, latest image kpeiruza/jibri:20210112 solved the problem but post recording script to upload recording on dropbox is not enable. It would be great if that can be enabled or you can update this repo so that I can build image from here.
Thanks in advance.

**Comment by congthang1** [comment]
Hi, I got this error:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
unix:path=/var/run/dbus/system_bus_socket,guid=ab3a70c8876c032652b8ef3860142d96
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
icewm-session: using /root/.icewm for private configuration files
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-5-amd64 x86_64 Debian
Current Operating System: Linux jibri-5dc647bf84-c7fkb 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-11-amd64 root=UUID=4e8b8101-6a06-429a-aaca-0ccd7ff14aa1 ro cgroup_enable=memory swapaccount=1 nosplash text biosdevname=0 net.ifnames=0 console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200 consoleblank=0 systemd.show_status=true
Build Date: 30 August 2020  03:55:49PM
xorg-server 2:1.19.2-1+deb9u6 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/xorg.log", Time: Fri Jan 29 22:45:26 2021
(++) Using config file: "/etc/jitsi/jibri/xorg-video-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
icewmbg: using /root/.icewm for private configuration files
IceWM: using /root/.icewm for private configuration files
icewmtray: using /root/.icewm for private configuration files
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-01-29 22:45:30.525 SEVERE: [25] org.jitsi.xmpp.mucclient.MucClient.log() Failed to initialize and start a MucClient: 
java.lang.NumberFormatException: For input string: "<no value>"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jitsi.xmpp.mucclient.MucClient.createXMPPTCPConnectionConfiguration(MucClient.java:111)
	at org.jitsi.xmpp.mucclient.MucClient.initializeConnectAndJoin(MucClient.java:250)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$start$0(MucClient.java:213)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Is this prevent jibri to start?

**Comment by kpeiruza** [comment]
Looks like some XMPP_ variable is missing.


*--> Failed to initialize and start a MucClient:
java.lang.NumberFormatException: For input string: "<no value>" at
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) *

Please mind to provide XMPP_PORT=5222 for standard setups using this Docker
Image.

We've modified Jibri to accept passing that port because we're using it in
loadbalancers serving several Jitsi Shards. Otherwise, the variable missing
is a standard one.

Best regards,

Kenneth

Missatge de Cong Thang <notifications@github.com> del dia dv., 29 de gen.
2021 a les 16:59:

**Comment by congthang1** [comment]
Thanks @kpeiruza that error gone when I put XMPP_PORT to 5222
Now I close to it just got an other error when starting Jibri session:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
unix:path=/var/run/dbus/system_bus_socket,guid=d87530e2aeedcffb745e1a636022508b
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
icewm-session: using /root/.icewm for private configuration files
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
X.Org X Server 1.19.2
Release Date: 2017-03-02
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-5-amd64 x86_64 Debian
Current Operating System: Linux jibri-web-697b64b4f5-lcgcc 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.19.0-11-amd64 root=UUID=4e8b8101-6a06-429a-aaca-0ccd7ff14aa1 ro cgroup_enable=memory swapaccount=1 nosplash text biosdevname=0 net.ifnames=0 console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200 consoleblank=0 systemd.show_status=true
Build Date: 30 August 2020  03:55:49PM
xorg-server 2:1.19.2-1+deb9u6 (https://www.debian.org/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/xorg.log", Time: Tue Feb  9 16:06:20 2021
(++) Using config file: "/etc/jitsi/jibri/xorg-video-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
IceWM: using /root/.icewm for private configuration files
icewmbg: using /root/.icewm for private configuration files
icewmtray: using /root/.icewm for private configuration files
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-02-09 16:06:21.882 WARNING: [26] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
Starting ChromeDriver 86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}) on port 10835

Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

**2021-02-09 16:06:38.813 SEVERE: [51] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED**

  (Session info: chrome=86.0.4240.183)
  (Driver info: chromedriver=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}),platform=Linux 4.19.0-11-amd64 x86_64) (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'jibri-web-697b64b4f5-lcgcc', ip: '10.244.1.165', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.0-11-amd64', java.version: '1.8.0_265'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: /tmp/.com.google.Chrome.DQzm0p}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:41845}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 86.0.4240.183, webStorageEnabled: true, webauthn:virtualAuthenticators: true}
Session ID: c297547e09a550f4b3536a793e884b80 with stack: 
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:28)
org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:237)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
2021-02-09 16:06:49.057 SEVERE: [51] org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize() Timed out waiting for process logger task to complete
` 
Did you ever seen this error. My XMPP_SERVER is public domain meet.mydomain.com and all other domain is internal domains.
Thanks.

**Comment by marcoadasilvaa** [comment]
Same error here!

i try on version pulse, 20210112 and own compile with base java stretch version 

Some chrome log errors interesting...

```
[1613875427.520][INFO]: Waiting for pending navigations...
[1613875427.521][INFO]: Done waiting for pending navigations. Status: ok
[1613875427.524][INFO]: Waiting for pending navigations...
[1613875427.524][INFO]: Done waiting for pending navigations. Status: ok
[1613875427.524][INFO]: [74380bbf0cde9c4c7624dc4ec0c9fb1d] RESPONSE ExecuteScript "APP is not defined"
[1613875427.528][INFO]: [74380bbf0cde9c4c7624dc4ec0c9fb1d] COMMAND Quit {

}
[1613875427.578][INFO]: [74380bbf0cde9c4c7624dc4ec0c9fb1d] RESPONSE Quit
root@jibri-5d598bb6f7-2lzj8:/tmp# 
root@jibri-5d598bb6f7-2lzj8:/tmp# 
root@jibri-5d598bb6f7-2lzj8:/tmp# cat chromedriver.log 
[1613875419.653][INFO]: Starting ChromeDriver 86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}) on port 23033
[1613875419.653][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1613875419.725][SEVERE]: bind() failed: Cannot assign requested address (99)
[1613875419.725][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID
[1613875420.126][INFO]: [74380bbf0cde9c4c7624dc4ec0c9fb1d] COMMAND InitSession {

[1613875420.126][INFO]: Launching chrome: /usr/bin/google-chrome --autoplay-policy=no-user-gesture-required --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --enabled --kiosk --log-level=0 --no-first-run --password-store=basic --remote-debugging-port=0 --start-maximized --test-type=webdriver --use-fake-ui-for-media-stream --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.rlL4WO data:,
[1613875425.467][INFO]: resolved localhost to ["127.0.0.1","::1"]
[1613875426.944][INFO]: [74380bbf0cde9c4c7624dc4ec0c9fb1d] RESPONSE InitSession {
   "acceptInsecureCerts": false,
   "acceptSslCerts": false,
   "applicationCacheEnabled": false,
   "browserConnectionEnabled": false,
   "browserName": "chrome",
   "chrome": {
      "chromedriverVersion": "86.0.4240.22 `(398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378})",`

```

**Comment by congthang1** [comment]
@kpeiruza could you share your yaml file of this jibri image?
Thank you.

**Comment by congthang1** [comment]
@kpeiruza  I see new docker file, how to get it run please!
I need to get rid of docker host.

**Comment by congthang1** [comment]
I'm trying to run it with env and all it by HTTP api. `/jibri/api/v1.0/startService ` It returning 200 but then nothing happen even logs not showing anything.
